baseurl:
url: https://eeux.github.io
date_format: "ordinal"
title: "eeux's blog"
subtitle: "Think twice before do everything."
description: "eeux's blog"
keywords: eeux, cpp, programming, linux, os
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 0

author: eeux
organization: https://eeux.github.io
organization_url: https://eeux.github.io
github_username: eeux
location: 
email: gnulxj@gmail.com

navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  -
    href: /archives/
    label: Archives

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About

subscribe_rss: /feed.xml

markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
#collections:
#    wiki:
#        output: true
#        permalink: /wiki/:path/

repository: eeux/eeux.github.io

comments_provider: 
#disqus:
#    username: eeux

#lazy_load_disqus : false

simple_jekyll_search:
    fulltext: false
    limit: 10

google:
    analytics_id: UA-152806603-1
